### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by yz1311** [kurisu994/react-native-txim#15]
请问这个项目会长期维护吗?

我目前的一个项目，用的是旧版的sdk，目前存在一些无法解决的小问题，前一段时间我尝试替换为您的库，但是小问题很多，导致又放弃回去修修补补了。

如果长期维护的话，可以一起维护下，目前需要一个稳定点的版本

**Comment by kurisu994** [comment]
是考虑长时间维护，不过IOS这边我搞不定，比较头疼，有人一起当然很好。
